apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev
  namespace: dev

configMapGenerator:
  - name: api
    envs:
      - api.env
  - name: ui
    envs:
      - ui.env

generatorOptions:
  disableNameSuffixHash: true
